* current error in `3-flake-utils-example-home-manager-spotify-using-agenix`:

#+begin_src sh
$ nixos-rebuild build-vm --flake .#Rick
building the system configuration...
error: cannot look up '<nixpkgs>' in pure evaluation mode (use '--impure' to override)

       at /nix/store/vxnx5a365sl90d64r8ajmbsxivybpa4m-source/modules/modules.nix:240:11:

          239|         else
          240|           <nixpkgs>);
             |           ^
          241|       _module.args.pkgs = lib.mkDefault pkgs;
(use '--show-trace' to show detailed location information)
#+end_src

* show trace output

#+begin_details
building the system configuration...
error: cannot look up '<nixpkgs>' in pure evaluation mode (use '--impure' to override)

       at /nix/store/vxnx5a365sl90d64r8ajmbsxivybpa4m-source/modules/modules.nix:240:11:

          239|         else
          240|           <nixpkgs>);
             |           ^
          241|       _module.args.pkgs = lib.mkDefault pkgs;

       … while evaluating the attribute 'value.content'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:925:14:

          924|     { _type = "override";
          925|       inherit priority content;
             |              ^
          926|     };

       … while evaluating the attribute 'value._type'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:878:73:

          877|       highestPrio = foldl' (prio: def: min (getPrio def) prio) 9999 defs;
          878|       strip = def: if def.value._type or "" == "override" then def // { value = def.value.content; } else def;
             |                                                                         ^
          879|     in {

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:777:19:

          776|           # Avoid sorting if we don't have to.
          777|           if any (def: def.value._type or "" == "order") defs''.values
             |                   ^
          778|           then sortProperties defs''.values

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:777:14:

          776|           # Avoid sorting if we don't have to.
          777|           if any (def: def.value._type or "" == "order") defs''.values
             |              ^
          778|           then sortProperties defs''.values

       … while evaluating the attribute 'values'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:781:9:

          780|       in {
          781|         values = defs''';
             |         ^
          782|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'optionalValue.value'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:799:5:

          798|
          799|     optionalValue =
             |     ^
          800|       if isDefined then { value = mergedValue; }

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/types.nix:461:29:

          460|       merge = loc: defs:
          461|         zipAttrsWith (name: defs:
             |                             ^
          462|           let merged = mergeDefinitions (loc ++ [name]) elemType defs;

       … from call site

       … while evaluating the module argument `pkgsPath' in "/nix/store/vxnx5a365sl90d64r8ajmbsxivybpa4m-source/modules/misc/nixpkgs.nix":

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:501:44:

          500|       context = name: ''while evaluating the module argument `${name}' in "${key}":'';
          501|       extraArgs = builtins.mapAttrs (name: _:
             |                                            ^
          502|         builtins.addErrorContext (context name)

       … from call site

       … while realising the context of a path

       at /nix/store/vxnx5a365sl90d64r8ajmbsxivybpa4m-source/modules/misc/nixpkgs.nix:52:11:

           51|
           52|   _pkgs = import pkgsPath (
             |           ^
           53|     filterAttrs (n: v: v != null) config.nixpkgs

       … while evaluating the attribute 'value.content'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:925:14:

          924|     { _type = "override";
          925|       inherit priority content;
             |              ^
          926|     };

       … while evaluating the attribute 'value._type'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:878:73:

          877|       highestPrio = foldl' (prio: def: min (getPrio def) prio) 9999 defs;
          878|       strip = def: if def.value._type or "" == "override" then def // { value = def.value.content; } else def;
             |                                                                         ^
          879|     in {

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:777:19:

          776|           # Avoid sorting if we don't have to.
          777|           if any (def: def.value._type or "" == "order") defs''.values
             |                   ^
          778|           then sortProperties defs''.values

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:777:14:

          776|           # Avoid sorting if we don't have to.
          777|           if any (def: def.value._type or "" == "order") defs''.values
             |              ^
          778|           then sortProperties defs''.values

       … while evaluating the attribute 'values'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:781:9:

          780|       in {
          781|         values = defs''';
             |         ^
          782|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'optionalValue.value'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:799:5:

          798|
          799|     optionalValue =
             |     ^
          800|       if isDefined then { value = mergedValue; }

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/types.nix:461:29:

          460|       merge = loc: defs:
          461|         zipAttrsWith (name: defs:
             |                             ^
          462|           let merged = mergeDefinitions (loc ++ [name]) elemType defs;

       … from call site

       … while evaluating the module argument `pkgs' in "/nix/store/vxnx5a365sl90d64r8ajmbsxivybpa4m-source/modules/config/i18n.nix":

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:501:44:

          500|       context = name: ''while evaluating the module argument `${name}' in "${key}":'';
          501|       extraArgs = builtins.mapAttrs (name: _:
             |                                            ^
          502|         builtins.addErrorContext (context name)

       … from call site

       … while evaluating 'versionOlder'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/strings.nix:562:22:

          561|   */
          562|   versionOlder = v1: v2: compareVersions v2 v1 == 1;
             |                      ^
          563|

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/strings.nix:574:29:

          573|   */
          574|   versionAtLeast = v1: v2: !versionOlder v1 v2;
             |                             ^
          575|

       … while evaluating 'versionAtLeast'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/strings.nix:574:24:

          573|   */
          574|   versionAtLeast = v1: v2: !versionOlder v1 v2;
             |                        ^
          575|

       … from call site

       at /nix/store/vxnx5a365sl90d64r8ajmbsxivybpa4m-source/modules/config/i18n.nix:29:19:

           28|   # lookup the version of glibcLocales and set the appropriate environment vars
           29|   localeVars = if versionAtLeast version "2.27" then {
             |                   ^
           30|     LOCALE_ARCHIVE_2_27 = archivePath;

       … while evaluating the attribute 'value'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:588:44:

          587|       defnsByName' = byName "config" (module: value:
          588|           [{ inherit (module) file; inherit value; }]
             |                                            ^
          589|         ) configs;

       … while evaluating 'dischargeProperties'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:839:25:

          838|   */
          839|   dischargeProperties = def:
             |                         ^
          840|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:768:137:

          767|         defs' = concatMap (m:
          768|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          769|         ) defs;

       … while evaluating definitions from `/nix/store/vxnx5a365sl90d64r8ajmbsxivybpa4m-source/modules/config/i18n.nix':

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:767:28:

          766|         # Process mkMerge and mkIf properties.
          767|         defs' = concatMap (m:
             |                            ^
          768|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:767:17:

          766|         # Process mkMerge and mkIf properties.
          767|         defs' = concatMap (m:
             |                 ^
          768|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:880:7:

          879|     in {
          880|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          881|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:781:9:

          780|       in {
          781|         values = defs''';
             |         ^
          782|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:787:5:

          786|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          787|     mergedValue =
             |     ^
          788|       if isDefined then

       … while evaluating the option `virtualisation.vmVariant.home-manager.users.morty.systemd.user.sessionVariables':

       … while evaluating the attribute 'value'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:753:9:

          752|     in warnDeprecation opt //
          753|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          754|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:302:72:

          301|           # For definitions that have an associated option
          302|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          303|

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/attrsets.nix:401:20:

          400|               then recurse (path ++ [name]) value
          401|               else f (path ++ [name]) value;
             |                    ^
          402|         in mapAttrs g;

       … while evaluating 'g'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/attrsets.nix:398:19:

          397|           g =
          398|             name: value:
             |                   ^
          399|             if isAttrs value && cond value

       … from call site

       … while evaluating the attribute 'assertion'

       at /nix/store/vxnx5a365sl90d64r8ajmbsxivybpa4m-source/modules/systemd.nix:244:11:

          243|         {
          244|           assertion = enabled -> pkgs.stdenv.isLinux;
             |           ^
          245|           message =

       … while evaluating the attribute 'assertion'

       at /nix/store/vxnx5a365sl90d64r8ajmbsxivybpa4m-source/nixos/default.nix:111:28:

          110|       flip map config.assertions (assertion: {
          111|         inherit (assertion) assertion;
             |                            ^
          112|         message = "${user} profile: ${assertion.message}";

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/nixos/modules/system/activation/top-level.nix:132:50:

          131|
          132|   failedAssertions = map (x: x.message) (filter (x: !x.assertion) config.assertions);
             |                                                  ^
          133|

       … from call site

       … while evaluating 'fold''

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/lists.nix:56:15:

           55|       len = length list;
           56|       fold' = n:
             |               ^
           57|         if n == len

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/lists.nix:60:8:

           59|         else op (elemAt list n) (fold' (n + 1));
           60|     in fold' 0;
             |        ^
           61|

       … while evaluating 'foldr'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/lists.nix:53:20:

           52|   */
           53|   foldr = op: nul: list:
             |                    ^
           54|     let

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/nixos/modules/system/activation/top-level.nix:139:12:

          138|   # Replace runtime dependencies
          139|   system = foldr ({ oldDependency, newDependency }: drv:
             |            ^
          140|       pkgs.replaceDependency { inherit oldDependency newDependency drv; }

       … while evaluating the attribute 'value'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:588:44:

          587|       defnsByName' = byName "config" (module: value:
          588|           [{ inherit (module) file; inherit value; }]
             |                                            ^
          589|         ) configs;

       … while evaluating 'dischargeProperties'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:839:25:

          838|   */
          839|   dischargeProperties = def:
             |                         ^
          840|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:768:137:

          767|         defs' = concatMap (m:
          768|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          769|         ) defs;

       … while evaluating definitions from `/nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:767:28:

          766|         # Process mkMerge and mkIf properties.
          767|         defs' = concatMap (m:
             |                            ^
          768|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:767:17:

          766|         # Process mkMerge and mkIf properties.
          767|         defs' = concatMap (m:
             |                 ^
          768|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:880:7:

          879|     in {
          880|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          881|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:781:9:

          780|       in {
          781|         values = defs''';
             |         ^
          782|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:787:5:

          786|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          787|     mergedValue =
             |     ^
          788|       if isDefined then

       … while evaluating the option `virtualisation.vmVariant.system.build.toplevel':

       … while evaluating the attribute 'value'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:753:9:

          752|     in warnDeprecation opt //
          753|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          754|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/modules.nix:302:72:

          301|           # For definitions that have an associated option
          302|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          303|

       … from call site

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/attrsets.nix:401:20:

          400|               then recurse (path ++ [name]) value
          401|               else f (path ++ [name]) value;
             |                    ^
          402|         in mapAttrs g;

       … while evaluating 'g'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/attrsets.nix:398:19:

          397|           g =
          398|             name: value:
             |                   ^
          399|             if isAttrs value && cond value

       … from call site

       … while evaluating anonymous lambda

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/lib/attrsets.nix:518:24:

          517|     let f = attrPath:
          518|       zipAttrsWith (n: values:
             |                        ^
          519|         let here = attrPath ++ [n]; in

       … from call site

       … while evaluating the attribute 'buildCommand' of the derivation 'nixos-vm'

       at /nix/store/8x9s4zv7dzmwxmm8lhsxk3nf8lxlh52q-source/pkgs/stdenv/generic/make-derivation.nix:270:7:

          269|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          270|       name =
             |       ^
          271|         let
#+end_details
